"""Python reference for the cost panel of the analyst session 8 bench.

1. Writes assets/aws-sample.js (layout metadata + prices) with json.dumps.
2. Recomputes, independently of assets/aws-cost.js, the bytes scanned and dollars for the canon
   query ladder, and prints them. compare-cost.js prints the same lines from the JS engine.
3. With --answers <layouts dir>: runs each canon query in DuckDB on all three layouts and checks
   that the answers are identical (a cheaper layout must not be a different answer).
"""
import json, math, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
META = json.load(open(os.path.join(HERE, "taxi-layout-metadata.json")))
PRICES = json.load(open(os.path.join(HERE, "prices-us-east-1.json")))
MB, GB, TB = 2 ** 20, 2 ** 30, 2 ** 40

QUERIES = [
    {"id": "Q1", "label": "Every column, the whole month", "cols": META["columns"], "from": None, "to": None,
     "sql": "SELECT * FROM trips"},
    {"id": "Q2", "label": "Average tip by payment type, the whole month", "cols": ["payment_type", "tip_amount"], "from": None, "to": None,
     "sql": "SELECT payment_type, ROUND(AVG(tip_amount), 4) AS avg_tip, COUNT(*) AS n FROM trips GROUP BY 1 ORDER BY 1"},
    {"id": "Q3", "label": "Fares on one day (15 January)", "cols": ["fare_amount"], "from": "2024-01-15", "to": "2024-01-15",
     "sql": "SELECT COUNT(*) AS n, ROUND(SUM(fare_amount), 2) AS fares FROM trips WHERE {day} = DATE '2024-01-15'"},
    {"id": "Q4", "label": "Trips per pickup zone, one week (15 to 21 January)", "cols": ["PULocationID"], "from": "2024-01-15", "to": "2024-01-21",
     "sql": "SELECT PULocationID, COUNT(*) AS n FROM trips WHERE {day} BETWEEN DATE '2024-01-15' AND DATE '2024-01-21' GROUP BY 1 ORDER BY 2 DESC, 1 LIMIT 5"},
]
LAYOUTS = ["csv", "parquet", "partitioned"]


def scanned(layout, q):
    filt = q["from"] is not None
    if layout == "csv":
        return META["csv"]["bytes"]
    if layout == "parquet":
        p = META["parquet"]
        cols = list(q["cols"]) + (["tpep_pickup_datetime"] if filt and "tpep_pickup_datetime" not in q["cols"] else [])
        return p["bytes"] - sum(p["cols"].values()) + sum(p["cols"][c] for c in cols)
    tot = 0
    for f in META["partitioned"]:
        if filt and not (q["from"] <= f["day"] <= q["to"]):
            continue
        tot += f["bytes"] - sum(f["cols"].values()) + sum(f["cols"][c] for c in q["cols"])
    return tot


def athena(b, usd_tb):
    billed = max(10, math.ceil(b / MB))
    return billed, billed * MB / TB * usd_tb


def tiered(gb, rows):
    cost = 0.0
    for r in rows:
        lo, hi = float(r["begin"]), (math.inf if r["end"] == "Inf" else float(r["end"]))
        if gb > lo:
            cost += (min(gb, hi) - lo) * r["usd"]
    return cost


def stored(layout):
    return {"csv": META["csv"]["bytes"], "parquet": META["parquet"]["bytes"], "partitioned": META["partitioned_bytes"]}[layout]


def write_asset():
    keep = {
        "region": PRICES["region"], "retrieved": PRICES["retrieved"], "source": PRICES["source"],
        "athena_tb": PRICES["athena"]["SCAN_TB"][0]["usd"],
        "athena_pub": PRICES["athena"]["SCAN_TB"][0]["publicationDate"][:10],
        "s3": {k: [{"begin": r["begin"], "end": r["end"], "usd": r["usd"]} for r in v]
               for k, v in PRICES["s3"].items() if v[0]["unit"] == "GB-Mo"},
        "s3_pub": PRICES["s3"]["STANDARD"][0]["publicationDate"][:10],
    }
    data = {"meta": META, "prices": keep,
            "queries": [{k: q[k] for k in ("id", "label", "cols", "from", "to")} for q in QUERIES]}
    with open(os.path.join(REPO, "assets", "aws-sample.js"), "w") as f:
        f.write("/* generated by materials/aws_reference.py with json.dumps; do not edit by hand */\n")
        f.write("window.AWS_SAMPLE = " + json.dumps(data, separators=(",", ":")) + ";\n")


def canon(csv_gb=1024, queries_per_day=100):
    usd_tb = PRICES["athena"]["SCAN_TB"][0]["usd"]
    f = csv_gb * GB / META["csv"]["bytes"]
    lines = [f"sample rows {META['rows']} | csv {META['csv']['bytes']} | parquet {META['parquet']['bytes']} | partitioned {META['partitioned_bytes']} in {len(META['partitioned'])} files"]
    for q in QUERIES:
        for L in LAYOUTS:
            b = scanned(L, q)
            mb_s, usd_s = athena(b, usd_tb)
            mb_x, usd_x = athena(b * f, usd_tb)
            lines.append(f"{q['id']} {L:11s} sample_bytes {b:>9d} share_of_csv {b / META['csv']['bytes']:.4f} "
                         f"sample_usd {usd_s:.6f} | at {csv_gb} GB csv: {b * f / GB:,.1f} GB scanned ${usd_x:,.2f}/query ${usd_x * queries_per_day * 30:,.0f}/month")
    for L in LAYOUTS:
        gb = stored(L) * f / GB
        lines.append(f"store {L:11s} {gb:,.1f} GB  STANDARD ${tiered(gb, PRICES['s3']['STANDARD']):,.2f}/mo  "
                     f"STANDARD_IA ${tiered(gb, PRICES['s3']['STANDARD_IA']):,.2f}/mo  DEEP_ARCHIVE ${tiered(gb, PRICES['s3']['DEEP_ARCHIVE']):,.2f}/mo")
    return lines


def answers(layouts_dir):
    import duckdb
    c = duckdb.connect()
    src = {
        "csv": (f"read_csv_auto('{layouts_dir}/trips.csv')", "CAST(tpep_pickup_datetime AS DATE)"),
        "parquet": (f"'{layouts_dir}/trips.parquet'", "CAST(tpep_pickup_datetime AS DATE)"),
        "partitioned": (f"read_parquet('{layouts_dir}/partitioned/*/*.parquet', hive_partitioning=true)", "pickup_date"),
    }
    for q in QUERIES[1:]:
        res = {}
        for L, (rel, day) in src.items():
            res[L] = c.execute(q["sql"].replace("FROM trips", "FROM " + rel).format(day=day)).fetchall()
        same = res["csv"] == res["parquet"] == res["partitioned"]
        print(q["id"], "identical across layouts:", same, "|", res["parquet"][:5])


if __name__ == "__main__":
    write_asset()
    for line in canon():
        print(line)
    if "--answers" in sys.argv:
        answers(sys.argv[sys.argv.index("--answers") + 1])
